// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/gofiber/fiber"
	"github.com/google/wire"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	app := NewApp()
	return app, nil
}

// server.go:

var Set = wire.NewSet(AppSet)
